version: '3.2'

services:
  resurface:
    image: resurfaceio/pilot:2.2.8
    container_name: jersey_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  jersey:
    image: test-jersey
    container_name: test_jersey_app
    ports:
      - '80:8080'
    env_file:
      - .env
