version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:2.3.1
    container_name: jersey_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  jersey:
    image: test-jersey
    container_name: jersey
    ports:
      - '80:8080'
    env_file:
      - .env
    volumes:
      - ${HOME}/.m2:/root/.m2